source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JZStackedView_Example', :exclusive => true do
  pod "JZStackedView", :path => "../"
end

target 'JZStackedView_Tests', :exclusive => true do
  pod "JZStackedView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
